## Impor Tools

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

## Impor Dataset

In [ ]:
df = pd.read_csv("padi_jabar.csv", header=0)
df

nama_kabupaten_kota      bulan  tahun  luas_panen  curah_hujan  \
0      KABUPATEN BANDUNG    JANUARI   2018         788       263.67   
1      KABUPATEN BANDUNG   FEBRUARI   2018        3449       511.52   
2      KABUPATEN BANDUNG      MARET   2018        4396       374.41   
3      KABUPATEN BANDUNG      APRIL   2018       12429       258.40   
4      KABUPATEN BANDUNG        MEI   2018        4385       126.56   
...                  ...        ...    ...         ...          ...   
1291    KOTA TASIKMALAYA    AGUSTUS   2021         701       111.65   
1292    KOTA TASIKMALAYA  SEPTEMBER   2021         484       178.92   
1293    KOTA TASIKMALAYA    OKTOBER   2021         476       291.16   
1294    KOTA TASIKMALAYA   NOVEMBER   2021         523       452.46   
1295    KOTA TASIKMALAYA   DESEMBER   2021         495       366.65   

      produksi_padi  
0              4667  
1             20625  
2             26289  
3             74341  
4             25796  
...             ...  
1291           4045  
1292           2533  
1293           2491  
1294           2740  
1295           2592  

[1296 rows x 6 columns]

## Menelaah Dataset

In [ ]:
df.shape

(1296, 6)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1296 entries, 0 to 1295
Data columns (total 6 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   nama_kabupaten_kota  1296 non-null   object 
 1   bulan                1296 non-null   object 
 2   tahun                1296 non-null   int64  
 3   luas_panen           1296 non-null   int64  
 4   curah_hujan          1296 non-null   float64
 5   produksi_padi        1296 non-null   int64  
dtypes: float64(1), int64(3), object(2)
memory usage: 60.9+ KB


## Membersihkan Outliers Data

In [ ]:
q1 = df.quantile(0.25)
q3 = df.quantile(0.75)
iqr = q3 - q1

df = df[~((df < (q1 - 1.5 * iqr)) | (df > (q3 + 1.5 * iqr))).any(axis = 1)]

<ipython-input-5-e9170ad3a9b1>:1: FutureWarning: The default value of numeric_only in DataFrame.quantile is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  q1 = df.quantile(0.25)
<ipython-input-5-e9170ad3a9b1>:2: FutureWarning: The default value of numeric_only in DataFrame.quantile is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  q3 = df.quantile(0.75)
<ipython-input-5-e9170ad3a9b1>:5: FutureWarning: Automatic reindexing on DataFrame vs Series comparisons is deprecated and will raise ValueError in a future version. Do `left, right = left.align(right, axis=1, copy=False)` before e.g. `left == right`
  df = df[~((df < (q1 - 1.5 * iqr)) | (df > (q3 + 1.5 * iqr))).any(axis = 1)]


In [ ]:
df.shape

(1205, 6)

## Memisahkan Fitur Independen dan Fitur Dependen

In [ ]:
X = df[['luas_panen', 'curah_hujan']]
Y = df['produksi_padi']

## Membagi Data Latih dan Data Uji dengan Split 90:10

In [ ]:
X_train_91, X_test_91, Y_train_91, Y_test_91 = train_test_split(X, Y, test_size = 0.1, random_state = 42)

## Membagi Data Latih dan Data Uji dengan Split 80:20

In [ ]:
X_train_82, X_test_82, Y_train_82, Y_test_82 = train_test_split(X, Y, test_size = 0.2, random_state = 42)

## Membagi Data Latih dan Data Uji dengan Split 70:30

In [ ]:
X_train_73, X_test_73, Y_train_73, Y_test_73 = train_test_split(X, Y, test_size = 0.3, random_state = 42)

## Membagi Data Latih dan Data Uji dengan Split 60:40

In [ ]:
X_train_64, X_test_64, Y_train_64, Y_test_64 = train_test_split(X, Y, test_size = 0.4, random_state = 42)

## Membagi Data Latih dan Data Uji dengan Split 50:50

In [ ]:
X_train_55, X_test_55, Y_train_55, Y_test_55 = train_test_split(X, Y, test_size = 0.5, random_state = 42)

## Melatih Model Split 90:10

In [ ]:
lr_91 = LinearRegression()
lr_91.fit(X_train_91, Y_train_91)

LinearRegression()

In [ ]:
a_91 = lr_91.intercept_
a_91

-333.3687510938107

In [ ]:
b_91 = lr_91.coef_
b_91

array([5.5873268 , 1.19363894])

## Melatih Model Split 80:20

In [ ]:
lr_82 = LinearRegression()
lr_82.fit(X_train_82, Y_train_82)

LinearRegression()

In [ ]:
a_82 = lr_82.intercept_
a_82

-379.96158801329875

In [ ]:
b_82 = lr_82.coef_
b_82

array([5.59175361, 1.2945226 ])

## Melatih Model Split 70:30

In [ ]:
lr_73 = LinearRegression()
lr_73.fit(X_train_73, Y_train_73)

LinearRegression()

In [ ]:
a_73 = lr_73.intercept_
a_73

-511.6259763438866

In [ ]:
b_73 = lr_73.coef_
b_73

array([5.59495683, 1.64605644])

## Melatih Model Split 60:40

In [ ]:
lr_64 = LinearRegression()
lr_64.fit(X_train_64, Y_train_64)

LinearRegression()

In [ ]:
a_64 = lr_64.intercept_
a_64

-395.40957754787814

In [ ]:
b_64 = lr_64.coef_
b_64

array([5.56134244, 1.58369022])

## Melatih Model Split 50:50

In [ ]:
lr_55 = LinearRegression()
lr_55.fit(X_train_55, Y_train_55)

LinearRegression()

In [ ]:
a_55 = lr_55.intercept_
a_55

-351.2414242531704

In [ ]:
b_55 = lr_55.coef_
b_55

array([5.56985975, 1.49202943])

## Evaluasi Model Split 90:10

In [ ]:
eva_91 = lr_91.predict(X_test_91)

In [ ]:
rmse_91 = mean_squared_error(Y_test_91, eva_91, squared=False)
print('RMSE Model Split 0:0 =', rmse_91)

RMSE Model Split 0:0 = 2713.8985119146387


In [ ]:
r2_91 = r2_score(Y_test_91, eva_91) * 100
print(f'R-Squared Model Split 0:0 = {r2_91}%')

R-Squared Model Split 0:0 = 98.44233356098484%


## Evaluasi Model Split 80:20

In [ ]:
eva_82 = lr_82.predict(X_test_82)

In [ ]:
rmse_82 = mean_squared_error(Y_test_82, eva_82, squared=False)
print('RMSE Model Split 0:0 =', rmse_82)

RMSE Model Split 0:0 = 2518.810870863086


In [ ]:
r2_82 = r2_score(Y_test_82, eva_82) * 100
print(f'R-Squared Model Split 0:0 = {r2_82}%')

R-Squared Model Split 0:0 = 98.56806224139082%


## Evaluasi Model Split 70:30

In [ ]:
eva_73 = lr_73.predict(X_test_73)

In [ ]:
rmse_73 = mean_squared_error(Y_test_73, eva_73, squared=False)
print('RMSE Model Split 0:0 =', rmse_73)

RMSE Model Split 0:0 = 2513.6207082954497


In [ ]:
r2_73 = r2_score(Y_test_73, eva_73) * 100
print(f'R-Squared Model Split 0:0 = {r2_73}%')

R-Squared Model Split 0:0 = 98.65667298831904%


## Evaluasi Model Split 60:40

In [ ]:
eva_64 = lr_64.predict(X_test_64)

In [ ]:
rmse_64 = mean_squared_error(Y_test_64, eva_64, squared=False)
print('RMSE Model Split 0:0 =', rmse_64)

RMSE Model Split 0:0 = 2748.81406057505


In [ ]:
r2_64 = r2_score(Y_test_64, eva_64) * 100
print(f'R-Squared Model Split 0:0 = {r2_64}%')

R-Squared Model Split 0:0 = 98.49389143384893%


## Evaluasi Model Split 50:50

In [ ]:
eva_55 = lr_55.predict(X_test_55)

In [ ]:
rmse_55 = mean_squared_error(Y_test_55, eva_55, squared=False)
print('RMSE Model Split 0:0 =', rmse_55)

RMSE Model Split 0:0 = 2702.9387268861474


In [ ]:
r2_55 = r2_score(Y_test_55, eva_55) * 100
print(f'R-Squared Model Split 0:0 = {r2_55}%')

R-Squared Model Split 0:0 = 98.4541293193075%


## Resume Evaluasi Model

In [ ]:
a_b_para = [
    ('Model Split 90:10', a_91, b_91[0], b_91[1]),
    ('Model Split 80:20', a_82, b_82[0], b_82[1]),
    ('Model Split 70:30', a_73, b_73[0], b_73[1]),
    ('Model Split 60:40', a_64, b_64[0], b_64[1]),
    ('Model Split 50:50', a_55, b_55[0], b_55[1])
]

a_b_show = pd.DataFrame(data = a_b_para, columns=['Nama Model', 'Constant', 'luas_panen Coefficient', 'curah_hujan Coefficient'])
a_b_show

Nama Model    Constant  luas_panen Coefficient  \
0  Model Split 90:10 -333.368751                5.587327   
1  Model Split 80:20 -379.961588                5.591754   
2  Model Split 70:30 -511.625976                5.594957   
3  Model Split 60:40 -395.409578                5.561342   
4  Model Split 50:50 -351.241424                5.569860   

   curah_hujan Coefficient  
0                 1.193639  
1                 1.294523  
2                 1.646056  
3                 1.583690  
4                 1.492029

In [ ]:
eva_para = [
    ('Model Split 90:10', rmse_91, r2_91),
    ('Model Split 80:20', rmse_82, r2_82),
    ('Model Split 70:30', rmse_73, r2_73),
    ('Model Split 60:40', rmse_64, r2_64),
    ('Model Split 50:50', rmse_55, r2_55),
]

eva_show = pd.DataFrame(data = eva_para, columns=['Nama Model', 'RMSE', 'R²'])
eva_show.sort_values(by=['RMSE'], ascending=True, inplace=True)
eva_show

Nama Model         RMSE         R²
2  Model Split 70:30  2513.620708  98.656673
1  Model Split 80:20  2518.810871  98.568062
4  Model Split 50:50  2702.938727  98.454129
0  Model Split 90:10  2713.898512  98.442334
3  Model Split 60:40  2748.814061  98.493891